version: '3'
services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ../app:/var/www
  php:
    build:
      context: ..
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ../app:/var/www
  mysql:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'secret'
      MYSQL_USER: 'yordas_user'
      MYSQL_PASSWORD: 'secret'
      MYSQL_DATABASE: 'yordas_db'
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - 3306:3306
volumes:
  mysqldata: {}
